export const LOADING_NEWS = 'LOADING_NEWS';
export const FETCHING_NEWS = 'FETCHING_NEWS';
export const CLEAR_NEWS = 'CLEAR_NEWS';

export const LOADING_SINGLE_NEWS = 'LOADING_SINGLE_NEWS';
export const FETCH_SINGLE_NEWS = 'FETCH_SINGLE_NEWS';
export const CLEAR_SINGLE_NEWS = 'CLEAR_SINGLE_NEWS';

export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const FETCHING_COMMENTS = 'FETCHING_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';

export const SWITCH_NEWS_FLAG = 'SWITCH_NEWS_FLAG';
export const SWITCH_COMMENTS_FLAG = 'SWITCH_COMMENTS_FLAG';