export const CREATE_NEWS_PAGE = 'CREATE_NEWS_PAGE';
export const REMOVE_NEWS_PAGE = 'REMOVE_NEWS_PAGE';

export const LOADING_NEWS = 'LOADING_NEWS';
export const FETCHING_NEWS = 'FETCHING_NEWS';

export const LOADING_SINGLE_NEWS = 'LOADING_SINGLE_NEWS';
export const FETCH_SINGLE_NEWS = 'FETCH_SINGLE_NEWS';