export const LOADING_NEWS = 'LOADING_NEWS';
export const FETCHING_NEWS = 'FETCHING_NEWS';

export const LOADING_SINGLE_NEWS = 'LOADING_SINGLE_NEWS';
export const FETCH_SINGLE_NEWS = 'FETCH_SINGLE_NEWS';

export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';